/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as IngresoDatosRouteImport } from './routes/ingreso-datos'
import { Route as InterrupcionesRouteImport } from './routes/interrupciones'
import { Route as QuieroLuzRouteImport } from './routes/quiero-luz'
import { Route as SigueTuVisitaRouteImport } from './routes/sigue-tu-visita'
import { Route as NoticiasIndexRouteImport } from './routes/noticias.index'
import { Route as NoticiasSlugRouteImport } from './routes/noticias.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const IngresoDatosRoute = IngresoDatosRouteImport.update({
  id: '/ingreso-datos',
  path: '/ingreso-datos',
  getParentRoute: () => rootRouteImport,
} as any)
const InterrupcionesRoute = InterrupcionesRouteImport.update({
  id: '/interrupciones',
  path: '/interrupciones',
  getParentRoute: () => rootRouteImport,
} as any)
const QuieroLuzRoute = QuieroLuzRouteImport.update({
  id: '/quiero-luz',
  path: '/quiero-luz',
  getParentRoute: () => rootRouteImport,
} as any)
const SigueTuVisitaRoute = SigueTuVisitaRouteImport.update({
  id: '/sigue-tu-visita',
  path: '/sigue-tu-visita',
  getParentRoute: () => rootRouteImport,
} as any)
const NoticiasIndexRoute = NoticiasIndexRouteImport.update({
  id: '/noticias/',
  path: '/noticias/',
  getParentRoute: () => rootRouteImport,
} as any)
const NoticiasSlugRoute = NoticiasSlugRouteImport.update({
  id: '/noticias/$slug',
  path: '/noticias/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ingreso-datos': typeof IngresoDatosRoute
  '/interrupciones': typeof InterrupcionesRoute
  '/quiero-luz': typeof QuieroLuzRoute
  '/sigue-tu-visita': typeof SigueTuVisitaRoute
  '/noticias/$slug': typeof NoticiasSlugRoute
  '/noticias/': typeof NoticiasIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ingreso-datos': typeof IngresoDatosRoute
  '/interrupciones': typeof InterrupcionesRoute
  '/quiero-luz': typeof QuieroLuzRoute
  '/sigue-tu-visita': typeof SigueTuVisitaRoute
  '/noticias/$slug': typeof NoticiasSlugRoute
  '/noticias': typeof NoticiasIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/ingreso-datos': typeof IngresoDatosRoute
  '/interrupciones': typeof InterrupcionesRoute
  '/quiero-luz': typeof QuieroLuzRoute
  '/sigue-tu-visita': typeof SigueTuVisitaRoute
  '/noticias/$slug': typeof NoticiasSlugRoute
  '/noticias/': typeof NoticiasIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/ingreso-datos'
    | '/interrupciones'
    | '/quiero-luz'
    | '/sigue-tu-visita'
    | '/noticias/$slug'
    | '/noticias/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/ingreso-datos'
    | '/interrupciones'
    | '/quiero-luz'
    | '/sigue-tu-visita'
    | '/noticias/$slug'
    | '/noticias'
  id:
    | '__root__'
    | '/'
    | '/ingreso-datos'
    | '/interrupciones'
    | '/quiero-luz'
    | '/sigue-tu-visita'
    | '/noticias/$slug'
    | '/noticias/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  IngresoDatosRoute: typeof IngresoDatosRoute
  InterrupcionesRoute: typeof InterrupcionesRoute
  QuieroLuzRoute: typeof QuieroLuzRoute
  SigueTuVisitaRoute: typeof SigueTuVisitaRoute
  NoticiasSlugRoute: typeof NoticiasSlugRoute
  NoticiasIndexRoute: typeof NoticiasIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ingreso-datos': {
      id: '/ingreso-datos'
      path: '/ingreso-datos'
      fullPath: '/ingreso-datos'
      preLoaderRoute: typeof IngresoDatosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/interrupciones': {
      id: '/interrupciones'
      path: '/interrupciones'
      fullPath: '/interrupciones'
      preLoaderRoute: typeof InterrupcionesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quiero-luz': {
      id: '/quiero-luz'
      path: '/quiero-luz'
      fullPath: '/quiero-luz'
      preLoaderRoute: typeof QuieroLuzRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sigue-tu-visita': {
      id: '/sigue-tu-visita'
      path: '/sigue-tu-visita'
      fullPath: '/sigue-tu-visita'
      preLoaderRoute: typeof SigueTuVisitaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/noticias/': {
      id: '/noticias/'
      path: '/noticias'
      fullPath: '/noticias/'
      preLoaderRoute: typeof NoticiasIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/noticias/$slug': {
      id: '/noticias/$slug'
      path: '/noticias/$slug'
      fullPath: '/noticias/$slug'
      preLoaderRoute: typeof NoticiasSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  IngresoDatosRoute: IngresoDatosRoute,
  InterrupcionesRoute: InterrupcionesRoute,
  QuieroLuzRoute: QuieroLuzRoute,
  SigueTuVisitaRoute: SigueTuVisitaRoute,
  NoticiasSlugRoute: NoticiasSlugRoute,
  NoticiasIndexRoute: NoticiasIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
