/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as IngresoDatosRouteImport } from './routes/ingreso-datos'
import { Route as QuieroLuzRouteImport } from './routes/quiero-luz'
import { Route as SigueTuVisitaRouteImport } from './routes/sigue-tu-visita'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const IngresoDatosRoute = IngresoDatosRouteImport.update({
  id: '/ingreso-datos',
  path: '/ingreso-datos',
  getParentRoute: () => rootRouteImport,
} as any)
const QuieroLuzRoute = QuieroLuzRouteImport.update({
  id: '/quiero-luz',
  path: '/quiero-luz',
  getParentRoute: () => rootRouteImport,
} as any)
const SigueTuVisitaRoute = SigueTuVisitaRouteImport.update({
  id: '/sigue-tu-visita',
  path: '/sigue-tu-visita',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ingreso-datos': typeof IngresoDatosRoute
  '/quiero-luz': typeof QuieroLuzRoute
  '/sigue-tu-visita': typeof SigueTuVisitaRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ingreso-datos': typeof IngresoDatosRoute
  '/quiero-luz': typeof QuieroLuzRoute
  '/sigue-tu-visita': typeof SigueTuVisitaRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/ingreso-datos': typeof IngresoDatosRoute
  '/quiero-luz': typeof QuieroLuzRoute
  '/sigue-tu-visita': typeof SigueTuVisitaRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/ingreso-datos' | '/quiero-luz' | '/sigue-tu-visita'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/ingreso-datos' | '/quiero-luz' | '/sigue-tu-visita'
  id: '__root__' | '/' | '/ingreso-datos' | '/quiero-luz' | '/sigue-tu-visita'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  IngresoDatosRoute: typeof IngresoDatosRoute
  QuieroLuzRoute: typeof QuieroLuzRoute
  SigueTuVisitaRoute: typeof SigueTuVisitaRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ingreso-datos': {
      id: '/ingreso-datos'
      path: '/ingreso-datos'
      fullPath: '/ingreso-datos'
      preLoaderRoute: typeof IngresoDatosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quiero-luz': {
      id: '/quiero-luz'
      path: '/quiero-luz'
      fullPath: '/quiero-luz'
      preLoaderRoute: typeof QuieroLuzRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sigue-tu-visita': {
      id: '/sigue-tu-visita'
      path: '/sigue-tu-visita'
      fullPath: '/sigue-tu-visita'
      preLoaderRoute: typeof SigueTuVisitaRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  IngresoDatosRoute: IngresoDatosRoute,
  QuieroLuzRoute: QuieroLuzRoute,
  SigueTuVisitaRoute: SigueTuVisitaRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
